spring:
  application:
    name: person-service
  neo4j:
    uri: bolt://18.215.181.20:7687
    authentication:
      username: neo4j
      password: 6154277353
server:
  address: '0.0.0.0'
  port: 10011
