name: Deploy to ECS

on:
  push:
    branches: [main]

env:
  AWS_REGION: us-east-1
  AWS_ECS_CLUSTER: person-cluster
  AWS_ECS_SERVICE: person-service
  AWS_ECS_TASK_DEFINITION_FAMILY: person-task
  CONTAINER_NAME: person-service
  DOCKER_IMAGE: aledve/person-service:latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download current task definition
        id: task-def
        run: |
          aws ecs describe-task-definition --task-definition $AWS_ECS_TASK_DEFINITION_FAMILY > task-def.json
          cat task-def.json

      - name: Create new task definition
        id: new-task-def
        run: |
          jq '.taskDefinition | {
              family: .family,
              networkMode: .networkMode,
              requiresCompatibilities: .requiresCompatibilities,
              cpu: .cpu,
              memory: .memory,
              executionRoleArn: .executionRoleArn,
              containerDefinitions: [.containerDefinitions[] | 
                if .name == env.CONTAINER_NAME then
                  .image = env.DOCKER_IMAGE | .
                else
                  .
                end
              ]
          }' task-def.json > new-task-def.json

      - name: Register new task definition
        id: register-task
        run: |
          new_task_def_arn=$(aws ecs register-task-definition --cli-input-json file://new-task-def.json | jq -r '.taskDefinition.taskDefinitionArn')
          echo "TASK_DEF_ARN=$new_task_def_arn" >> $GITHUB_ENV

      - name: Update ECS service to use new task definition
        run: |
          aws ecs update-service \
            --cluster $AWS_ECS_CLUSTER \
            --service $AWS_ECS_SERVICE \
            --task-definition $TASK_DEF_ARN
